config/routes.rb
Rails.application.routes.draw do
  
  get '/user/signup' => 'users#new'
  post '/user/signup' => 'users#create'
  get '/user/login' => 'users#login'
  post '/user/login' => 'users#signin'
  get '/users/:id' => 'users#profile', as: 'user_profile'
  get '/logout' => 'application#logout'

  get '/admin/signup' => 'admins#new'
  post '/admin/signup' => 'admins#create'
  get '/admin/login' => 'admins#login'
  post '/admin/login' => 'admins#signin'
  get '/admins/:id' => 'admins#profile', as: 'admin_profile'


  get '/user/home' => 'users#home'
  get '/admin/home' => 'admins#home'
  get '/auth/facebook/callback' => 'users#github'
  root 'application#welcome'

  resources :admins, only: [:show] do 
    resources :cafes, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

  resources :admins, only: [:show] do
    resources :foods, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

    resources :users, only: [:show] do 
      resources :bookings, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

    resources :cafes, only: [:show] do 
      resources :cafes_food, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

  resources :bookings, only: [:index, :show]
  resources :cafes, only: [:index, :show]
  # resources :cafes_food, only: [:index, :show]
  resources :foods, only: [:index, :show]
  resources :cafes_food, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/home.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Home', root_path, :class=> "active" %></li>
                <li><%= link_to 'Signup', admin_signup_path %></li>
                <li><%= link_to 'Login', admin_login_path %></li>
            </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->

<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="thai">
                <img src="/assets/thai.jpg" />
                    <h4>Thai Tanic</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="snacks">
                <img src="/assets/burger.jpg">
                     <h4>Evening Snacks</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="grill">
                <img src="/assets/gril.jpeg">
                      <h4>Gochew Grill</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
     
       <a href="#"><button class="btn">Read More</button></a>
                           
    
</body>
</html>

app/views/admins/login.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
             <li><%= link_to 'Home', root_path, :class=> "active" %></li>
             <li><%= link_to 'Signup', admin_signup_path %></li>
             <li><%= link_to 'Login', admin_login_path %></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome to our Login page!</h3> 
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
              <%= form_for @admin, url: '/admin/login' do |f| %>
                <div class="content">
                <%= f.label :email %>
                <%= f.text_field :email %> 
                <br>
                <br>
                <%= f.label :password %>
                <%= f.password_field :password %>
                <br>
                <br>
                <%= f.button "Login", :class => 'btn' %>
              <% end %>
              </div> 
           </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
                           
    
</body>
</html>

app/views/admins/new.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
             <li><%= link_to 'Home', root_path, :class=> "active" %></li>
             <li><%= link_to 'Signup', admin_signup_path %></li>
             <li><%= link_to 'Login', admin_login_path %></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome to our Sign-up page!</h3> 
<!--SHOWCASE-->

    <showcase>
        <div class="container">
          <h1>Food tastes better when you eat it with your family</h1>
          <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
              <%= form_for @admin, url: '/admin/signup' do |f| %>
                <% if @admin.errors.any? %>
                  <div id="error_explanation">
                  <h2>There were some errors:</h2>
                  <ul>
                    <% @admin.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                  </div>
                <% end %>
                <br>
                <br>
            <div class="content">
              <%= f.label :name %>
              <%= f.text_field :name %>
              <br>
              <br>
              <%= f.label :email %>
              <%= f.text_field :email %>
              <br>
              <br>
              <%= f.label :password %>
              <%= f.password_field :password %>
              <br>
              <br>
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation %>
              <br>
              <br>
              <%= f.button "Sign-up", :class => 'btn' %>
            <% end %>
            </div> 
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
                           
    
</body>
</html>

app/views/admins/profile.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="thai">
                <img src="/assets/thai.jpg">
                    <h4>Thai Tanic</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="snacks">
                <img src="/assets/burger.jpg">
                     <h4>Evening Snacks</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="grill">
                <img src="/assets/gril.jpeg">
                      <h4>Gochew Grill</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
    
                           
    
</body>
</html>

app/views/admins/show.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_food_path%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="thai">
                <img src="/assets/thai.jpg">
                    <h4>Thai Tanic</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="snacks">
                <img src="/assets/burger.jpg">
                     <h4>Evening Snacks</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="grill">
                <img src="/assets/gril.jpeg">
                      <h4>Gochew Grill</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
    
                           
    
</body>
</html>