config/routes.rb
Rails.application.routes.draw do
  
  get '/user/signup' => 'users#new'
  post '/user/signup' => 'users#create'
  get '/user/login' => 'users#login'
  post '/user/login' => 'users#signin'
  get '/users/:id' => 'users#profile', as: 'user_profile'
  get '/logout' => 'application#logout'

  get '/admin/signup' => 'admins#new'
  post '/admin/signup' => 'admins#create'
  get '/admin/login' => 'admins#login'
  post '/admin/login' => 'admins#signin'
  get '/admins/:id' => 'admins#profile', as: 'admin_profile'


  get '/user/home' => 'users#home'
  get '/admin/home' => 'admins#home'
  get '/auth/facebook/callback' => 'users#github'
  root 'application#welcome'

  resources :admins, only: [:show] do 
    resources :cafes, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

  resources :admins, only: [:show] do
    resources :foods, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

    resources :users, only: [:show] do 
      resources :bookings, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

    resources :cafes, only: [:show] do 
      resources :cafes_food, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

  resources :bookings, only: [:index, :show]
  resources :cafes, only: [:index, :show]
  # resources :cafes_food, only: [:index, :show]
  resources :foods, only: [:index, :show]
  resources :cafes_food, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    has_many :bookings
    has_many :cafes, through: :bookings
    accepts_nested_attributes_for :bookings

    validates :name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password, presence: true
    validates(:password, { :length => { :in => 6..20 } })
    validates :contact, presence: true
    validates :contact, length: { is: 10 }
    validates :contact, numericality: { only_integer: true }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def home 
    end 

    def new 
        @user = User.new 
    end 

    def create
       @user = User.new(user_params)
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to user_profile_path(@user) 
        else
            render "new"
        end 
    end 

    def login
        @user = User.new 
    end 

    def signin
        @user = User.find_by(email: params[:user][:email])
            if @user && @user.authenticate(params[:user][:password])
                session[:user_id] = @user.id
                redirect_to user_profile_path(@user)
            else 
                redirect_to user_login_path 
            end 
    end 

    def github
        @user = User.find_or_create_by(uid: auth['uid']) do |u|
            u.uid = auth['uid']
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(10)
            u.contact = rand.to_s[2..11]
        end
        session[:user_id] = @user.id
        redirect_to user_profile_path(@user)
    end 

    def profile 
        if is_logged_in?
            if current_user_type != "Admin"
              render "profile"
            else
              @admin = current_user
              redirect_to admin_profile_path(@admin)
            end
        else
            redirect_to '/'
        end
    end 

    private 

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :contact)
    end 

    def auth
        request.env['omniauth.auth']
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Home', root_path, :class=> "active" %></li>
                <li><%= link_to 'Signup', user_signup_path %></li>
                <li><%= link_to 'Login', user_login_path %></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->

<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="thai">
                <img src="/assets/thai.jpg">
                    <h4>Thai Tanic</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="snacks">
                <img src="/assets/burger.jpg">
                     <h4>Evening Snacks</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="grill">
                <img src="/assets/gril.jpeg">
                      <h4>Gochew Grill</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
     
       <a href="#"><button class="btn">Read More</button></a>
                           
    
</body>
</html>

app/views/users/login.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Home', root_path, :class=> "active" %></li>
                <li><%= link_to 'Signup', user_signup_path %></li>
                <li><%= link_to 'Login', user_login_path %></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome to our Login page!</h3> 
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
            <%= form_for @user, url: '/user/login' do |f| %>
              <div class="content">
              <%= f.label :email %> 
              <%= f.text_field :email %> 
              <br>
              <br>
              <%= f.label :password %> 
              <%= f.password_field :password %>
              <br>
              <br>
              <%= f.button "Login", :class => 'btn' %>
              <% end %>
              <br>
              <p><%= link_to 'Log in with facebook!', '/auth/facebook' %></p>
              </div> 
           </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
                           
    
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Home', root_path, :class=> "active" %></li>
                <li><%= link_to 'Signup', user_signup_path %></li>
                <li><%= link_to 'Login', user_login_path %></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome to our Sign-up page!</h3> 
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
            <%= form_for @user, url: '/user/signup' do |f| %>
              <% if @user.errors.any? %>
                <div id="error_explanation">
                  <h2>There were some errors:</h2>
                  <ol>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ol>
                </div>
              <% end %>
            <br>
            <br>
            <div class="content">
            <%= f.label :name %>
            <%= f.text_field :name %> 
            <br>
            <br>
            <%= f.label :email %>
            <%= f.text_field :email %>
            <br>
            <br>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <br>
            <br>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
            <br>
            <br>
            <%= f.label :contact %>
            <%= f.text_field :contact %> 
            <br>
            <br>
           
            <%= f.button "Sign-up", :class => 'btn' %>
            <br>
            
            <% end %>
            
            </div> 
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
                           
    
</body>
</html>

app/views/users/profile.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>


<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', user_profile_path(current_user), :class=> "active" %></li>
                <li><%= link_to 'Make a booking', new_user_booking_path(current_user) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all bookings', user_bookings_path(current_user) %></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @user.name %> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="thai">
                <img src="/assets/thai.jpg">
                    <h4>Thai Tanic</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="snacks">
                <img src="/assets/burger.jpg">
                     <h4>Evening Snacks</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="grill">
                <img src="/assets/gril.jpeg">
                      <h4>Gochew Grill</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
    
                           
    
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', user_path(@user), :class=> "active" %></li>
                <li><%= link_to 'Make a booking', new_user_booking_path(@user) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all bookings', user_bookings_path(@user) %></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->

    <% if session[:user_id] %>
        <h1><%= @user.full_name %></h1>
    <% else %>
        <h3>Welcome <%= @user.full_name %> to your homepage!</h3>
    <% end %>

<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="thai">
                <img src="/assets/thai.jpg">
                    <h4>Thai Tanic</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="snacks">
                <img src="/assets/burger.jpg">
                     <h4>Evening Snacks</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
                <div class="grill">
                <img src="/assets/gril.jpeg">
                      <h4>Gochew Grill</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi aut vero sint itaque dignissimos, fugiat ipsum laboriosam </p>
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
    
                           
    
</body>
</html>