config/routes.rb
Rails.application.routes.draw do
  
  get '/user/signup' => 'users#new'
  post '/user/signup' => 'users#create'
  get '/user/login' => 'users#login'
  post '/user/login' => 'users#signin'
  get '/users/:id' => 'users#profile', as: 'user_profile'
  get '/logout' => 'application#logout'

  get '/admin/signup' => 'admins#new'
  post '/admin/signup' => 'admins#create'
  get '/admin/login' => 'admins#login'
  post '/admin/login' => 'admins#signin'
  get '/admins/:id' => 'admins#profile', as: 'admin_profile'


  get '/user/home' => 'users#home'
  get '/admin/home' => 'admins#home'
  get '/auth/facebook/callback' => 'users#github'
  root 'application#welcome'

  resources :admins, only: [:show] do 
    resources :cafes, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

  resources :admins, only: [:show] do
    resources :foods, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

    resources :users, only: [:show] do 
      resources :bookings, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

    resources :cafes, only: [:show] do 
      resources :cafes_food, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

  resources :bookings, only: [:index, :show]
  resources :cafes, only: [:index, :show]
  # resources :cafes_food, only: [:index, :show]
  resources :foods, only: [:index, :show]
  resources :cafes_food, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cafe.rb
class Cafe < ApplicationRecord
    has_many :bookings
    has_many :users, through: :bookings
    has_many :cafe_foods
    has_many :foods, through: :cafe_foods
    belongs_to :admin
    accepts_nested_attributes_for :foods

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :street, presence: true
    validates :street, uniqueness: true
    validates :city, presence: true
    validates :state, presence: true
    validates :state, length: { is: 2 }
    validates :zipcode, presence: true
    validates :zipcode, numericality: { only_integer: true }
    validates :zipcode, length: { is: 5 }

    def self.search(search)
        if search 
            cafe_type = Cafe.find_by(name: search)
            if cafe_type
                self.where(name: cafe_type.name)
            else 
                @cafes = Cafe.all
            end 
        else 
            @cafes = Cafe.all
        end 
    end 

    
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController

    def index 
      if is_logged_in?
        if params[:admin_id]
          @admin = Admin.find_by(id: params[:admin_id])
          if @admin.nil?
            redirect_to admin_profile_path(@admin), alert: "Admin not found."
          else 
            if @admin != current_user
               redirect_to admin_profile_path(current_user)
            else 
                @cafes = @admin.cafes.search(params[:search])
                # @cafes = Cafe.search(params[:search])
            end 
          end 
        else
          @cafes = @admin.cafes.search(params[:search])
          # @cafes = Cafe.search(params[:search])
        end
      else 
          redirect_to admin_login_path 
      end
    end 

    def show
      if is_logged_in?
        @admin = current_user
        @cafe = Cafe.find_by(params[:id])
          if @cafe.admin != @admin
            redirect_to admin_profile_path(@admin)
          end 
      else 
        redirect_to admin_login_path 
      end 
    end 


    def new 
      if is_logged_in?
        if params[:admin_id]
          @admin = Admin.find_by(id: params[:admin_id])
          if @admin.nil?
            redirect_to admin_profile_path(current_user), alert: "Admin not found."
          else 
            if @admin != current_user
               redirect_to admin_profile_path(current_user)
            else 
              @admin = current_user
              @cafe = @admin.cafes.build 
            end 
          end 
        else 
          admin_profile_path(current_user)
        end 
      else 
        redirect_to admin_login_path 
      end 
    end

    def create 
        @admin = current_user 
        @cafe = Cafe.new(cafe_params)
        if @cafe.save
          redirect_to admin_cafe_path(@admin,@cafe)
        else
          render "new"
        end
    end 

    def edit
        if is_logged_in?
          if params[:admin_id]
            @admin = Admin.find_by(id: params[:admin_id])
            if @admin.nil?
              redirect_to admin_profile_path(current_user), alert: "Admin not found."
            else
              @cafe = @admin.cafes.find_by(id: params[:id])
              redirect_to admin_cafes_path(@admin), alert: "Cafe not found." if @cafe.nil?
            end
          else
            @admin = current_user
            @cafe = Cafe.find(params[:id])
            if @cafe.admin != @admin 
              redirect_to admin_profile_path(@admin)
            end 
          end
        else 
          redirect_to admin_login_path
        end 
      end
  
        def update
          @admin = current_user 
          @cafe = Cafe.find_by_id(params[:id])
          @cafe.update(cafe_params)
          redirect_to admin_cafe_path(@admin,@cafe)
        end
  
        def destroy 
          if is_logged_in?
            if params[:admin_id]
              @admin = Admin.find_by(id: params[:admin_id])
              if @admin.nil?
                redirect_to admin_profile_path(current_user), alert: "Admin not found."
              else
                @cafe = @admin.cafes.find_by(id: params[:id])
                if @cafe.nil?
                  redirect_to admin_cafes_path(@admin), alert: "Cafe not found."
                else 
                  @cafe.delete
                  redirect_to admin_cafes_path(@admin)
                end 
              end 
            else
              @admin = current_user
              @cafe = Cafe.find(params[:id])
                if @cafe.admin != @admin
                  redirect_to admin_profile_path(@admin)
                else 
                  @cafe.delete
                  redirect_to admin_cafes_path(@admin)
                end 
            end 
         else 
            redirect_to admin_login_path
          end 
        end 

    private

  def cafe_params
    params.require(:cafe).permit(:admin_id, :name, :street, :city, :state, :zipcode, :search)
  end
end

app/views/cafes/_form.html.erb
<%= form_for [@admin, @cafe] do |f| %>
<% if @cafe.errors.any? %>
<div id="error_explanation">
<h2>There were some errors:</h2>
<ul>
  <% @cafe.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
</div>
<% end %>
<div class="content">
<h3> To add a new cafe fill out the fields below :</h3>
<%= f.hidden_field :admin_id %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :street %>
<%= f.text_field :street %>
<br>
<br>
<%= f.label :city %>
<%= f.text_field :city %>
<br>
<br>
<%= f.label :state %>
<%= f.text_field :state %>
<br>
<br>
<%= f.label :zipcode %>
<%= f.text_field :zipcode %>
<br>
<br>
<%= f.button "Add Cafe", :class => 'btn' %>
</div>
<% end %> 

app/views/cafes/edit.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
           
           
               <%= render 'form' %> 
          
           
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
    
</body>
</html>









    
    
     

app/views/cafes/index.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="content">
                    <%= form_tag admin_cafes_path(@admin), :method => "get" do %>
                        <%= text_field_tag :search, params[:search] %>
                        <%= submit_tag("Search", :name => nil)%>
                    <% end %> 
                <h2>The information of this cafe :</h2>
                <table class="content-table">
                            <thead>
                                <tr>
                                <th>Cafe Name</th>
                                <th>Street</th>
                                <th>State</th>
                                <th>City</th>
                                <th>Zipcode</th>
                                <th>Edit</th>
                                <th>Delete</th>
                                <th>View Menu</th>
                                <th>Add Menu Item</th>
                                </tr>
                            </thead>
                            <% @cafes.each do |c| %>
                            <tbody>
                                <tr>
                                <td><%= c.name %></td>
                                <td><%=c.street%></td>
                                <td><%=c.city%></td>
                                <td><%=c.state%></td>
                                <td><%=c.zipcode%></td>
                                <td><%= button_to('Edit', edit_admin_cafe_path(@admin, c), :method=>"get") %></td>
                                <td><%= button_to('Delete', admin_cafe_path(@admin, c), :method=>"delete") %></td>
                                <td><%= button_to('Add food menu', new_cafe_cafes_food_path(c.id), :method=> "get") %></td>
                                <td><%= button_to('View food menu', cafe_cafes_food_index_path(c.id), :method=> "get") %></td>
                                </tr>
                            </tbody>
                            <% end %>
                        </table>
                      
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->

</body>
</html>

app/views/cafes/new.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
           
            
              <%= render 'form' %> 
         
           
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->
    
</body>
</html>











    
    
     

app/views/cafes/show.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="content">
                <h2>The information of this cafe :</h2>
                <table class="content-table">
                            <thead>
                                <tr>
                                <th>Cafe Name</th>
                                <th>Street</th>
                                <th>State</th>
                                <th>City</th>
                                <th>Zipcode</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                <td><%= @cafe.name %></td>
                                <td><%=@cafe.street%></td>
                                <td><%=@cafe.city%></td>
                                <td><%=@cafe.state%></td>
                                <td><%=@cafe.zipcode%></td>
                                </tr>
                            </tbody>
                        </table>
                      
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->

</body>
</html>