config/routes.rb
Rails.application.routes.draw do
  
  get '/user/signup' => 'users#new'
  post '/user/signup' => 'users#create'
  get '/user/login' => 'users#login'
  post '/user/login' => 'users#signin'
  get '/users/:id' => 'users#profile', as: 'user_profile'
  get '/logout' => 'application#logout'

  get '/admin/signup' => 'admins#new'
  post '/admin/signup' => 'admins#create'
  get '/admin/login' => 'admins#login'
  post '/admin/login' => 'admins#signin'
  get '/admins/:id' => 'admins#profile', as: 'admin_profile'


  get '/user/home' => 'users#home'
  get '/admin/home' => 'admins#home'
  get '/auth/facebook/callback' => 'users#github'
  root 'application#welcome'

  resources :admins, only: [:show] do 
    resources :cafes, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

  resources :admins, only: [:show] do
    resources :foods, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  end 

    resources :users, only: [:show] do 
      resources :bookings, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

    resources :cafes, only: [:show] do 
      resources :cafes_food, only: [:index, :show, :new, :create, :update, :edit, :destroy]
    end 

  resources :bookings, only: [:index, :show]
  resources :cafes, only: [:index, :show]
  # resources :cafes_food, only: [:index, :show]
  resources :foods, only: [:index, :show]
  resources :cafes_food, only: [:index, :show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/cafes_food_controller.rb
class CafesFoodController < ApplicationController


    def index
      if is_logged_in?
        if params[:cafe_id]
          @cafe = Cafe.find_by(id: params[:cafe_id])
          if @cafe.nil?
            redirect_to admin_profile_path(current_user), alert: "Cafe not found."
          else 
            if !current_user.cafe_ids.include?(@cafe.id)
               redirect_to admin_profile_path(current_user)
            else 
              @cafes_food = @cafe.cafe_foods
            end 
          end 
        else
          redirect_to admin_profile_path(current_user)
        end
      else 
          redirect_to admin_login_path 
      end
    end

    def show 
        if is_logged_in?
            @admin = current_user
            @cafe = Cafe.find_by_id(params[:cafe_id])
            @cafe_food = CafeFood.find_by_id(params[:id])
            if @cafe_food != nil 
                @cafe_food_cafe_id = @cafe_food.cafe_id 
                    if !@admin.cafe_ids.include?(@cafe_food_cafe_id)
                        redirect_to admin_profile_path
                    end
            else 
                redirect_to admin_profile_path
            end 
        else 
            redirect_to admin_login_path 
        end 
    end 

    def new 
      if is_logged_in?
        if params[:cafe_id]
          @cafe = Cafe.find_by(id: params[:cafe_id])
          if @cafe.nil?
            redirect_to admin_profile_path(current_user), alert: "No such item found."
          else 
            if @cafe.admin != current_user
               redirect_to admin_profile_path(current_user)
            else 
              @admin = current_user
              @cf = @cafe.cafe_foods.build
            end 
          end 
        else 
          admin_profile_path(current_user)
        end 
      else 
        redirect_to admin_login_path 
      end 
    end 

     def create
        @admin = current_user 
        @cafe = Cafe.find_by_id(params[:cafe_id])
        @cf = CafeFood.new(cafe_food_params)
            if @cf.save
                redirect_to cafe_cafes_food_path(@cafe, @cf)
            else
                render :new
            end
    end

    def edit
        if is_logged_in?
            @admin = current_user
          if params[:cafe_id]
            @cafe = Cafe.find_by(id: params[:cafe_id])
            if @cafe.nil?
              redirect_to admin_profile_path(@admin), alert: "Cafe not found."
            else
              @cf = @cafe.cafe_foods.find_by(id: params[:id])
              redirect_to cafe_cafes_food_index_path(@cafe), alert: "Cafe Food not found." if @cf.nil?
            end
          else
            @admin = current_user
            @cf = CafeFood.find_by_id(params[:id])
              if !@admin.cafe_ids.include?(@cf.cafe_id)
                redirect_to admin_profile_path(@admin)
              end 
          end
        else 
          redirect_to admin_login_path 
        end 
      end
  
        def update
          @admin = current_user 
          @cafes_food = CafeFood.find(params[:id])
          @cafes_food.update(cafe_food_params)
          redirect_to cafe_cafes_food_path(@cafes_food.cafe, @cafes_food)
        end
  
      def destroy 
        if is_logged_in?
          @admin = current_user
        if params[:cafe_id]
          @cafe = Cafe.find_by(id: params[:cafe_id])
          if @cafe.nil?
            redirect_to admin_profile_path(@admin), alert: "Cafe not found."
          else
            @cafes_food = @cafe.cafe_foods.find_by(id: params[:id])
            if @cafes_food.nil?
              redirect_to cafe_cafes_food_index_path(@cafe), alert: "Cafe Food not found."
            else 
              @cafes_food.delete
              redirect_to cafe_cafes_food_index_path(@cafe)
            end 
          end
        else
          @admin = current_user
          @cafes_food = CafeFood.find_by_id(params[:id])
              if !@admin.cafe_ids.include?(@cafes_food.cafe_id)
                redirect_to admin_profile_path(@admin)
              else 
                @cafes_food.delete
                redirect_to cafe_cafes_food_index_path(@cafe)
              end 
        end 
      else 
        redirect_to admin_login_path 
      end
    end 

    private

  def cafe_food_params
    params.require(:cafe_food).permit(:cafe_id, :food_id, :price)
  end

end

app/helpers/cafes_food_helper.rb
module CafesFoodHelper
end

app/views/cafes_food/_form.html.erb
<%= form_for [@cafe,@cf] do |f| %>
<% if @cf.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @cf.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="content">
    Cafe : <%= f.collection_select :cafe_id, Cafe.all, :id, :name %>
    <br>
    <br>
    Food : <%= f.collection_select :food_id, Food.all, :id, :name %>
    <br>
    <br>
    <%= f.label :price %>
    <%= f.number_field :price %>
    <br>
    <br> 
    <%= f.button "Make a Cafe Food", :class => 'btn' %>
    <% end %>

app/views/cafes_food/edit.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
           


   <%= render 'form' %> 
 
</div>
</div>
</div>
</showcase> 
<!--   END OF SHOWCASE  -->

</body>
</html>

app/views/cafes_food/index.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="content">
                <h2>The information of this cafe :</h2>
                <table class="content-table">
                            <thead>
                                <tr>
                                <th>Cafe Name</th>
                                <th>Food Name</th>
                                <th>Food Price</th>
                                <th>Edit</th>
                                <th>Delete</th>
                                </tr>
                            </thead>
                            <% @cafes_food.each do |cf| %>
                            <tbody>
                                <tr>
                                <td><%= cf.cafe.name %></td>
                                <td><%= cf.food.name %></td>
                                <td><%= cf.price %></td>
                                <td><%= button_to('Edit', edit_cafe_cafes_food_path(cf.cafe, cf), :method=>"get") %></td>
                                <td><%= button_to('Delete', cafe_cafes_food_path(cf.cafe, cf), :method=>"delete") %></td>
                                </tr>
                            </tbody>
                            <% end %>
                        </table>
                      
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->

</body>
</html>

app/views/cafes_food/new.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
           

<%= form_for @cf, url: cafe_cafes_food_index_path(@cafe) do |f| %>
  <% if @cf.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @cf.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="content">
    Cafe : <%= f.collection_select :cafe_id, Cafe.all, :id, :name %>
    <br>
    <br>
    Food : <%= f.collection_select :food_id, Food.all, :id, :name %>
    <br>
    <br>
    <%= f.label :price %>
    <%= f.number_field :price %>
    <br>
    <br> 
    <%= f.button "Make a Cafe Food", :class => 'btn' %>
<% end %> 
</div>
</div>
</div>
</showcase> 
<!--   END OF SHOWCASE  -->

</body>
</html>

app/views/cafes_food/show.html.erb
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Web Template</title>
    <link rel="stylesheet" href="application.css">
</head>
<body>
   
<!--   HEADER  -->
  
  <header>
      <div class="head">
         <h2>Bellyful</h2> 
      </div>
<!--    NAVIGATION  -->
         <nav>
             <ul>
                <li><%= link_to 'Profile', admin_profile_path(@admin), :class=> "active" %></li>
                <li><%= link_to 'Add a Cafe', new_admin_cafe_path(@admin) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
                <li><%= link_to 'View all cafes', admin_cafes_path(@admin)%></li>
                <li><%= link_to 'Add new food', new_admin_food_path(@admin)%></li>
                <li><%= link_to 'View all foods', admin_foods_path(@admin)%></li>
             </ul>
         </nav>
<!--    END OF NAVIGATION  -->
  </header>
<!--  END OF HEADER  -->
<h3>Welcome <%= @admin.name%> to your homepage!</h3>
<!--SHOWCASE-->

    <showcase>
        <div class="container">
            <h1>Food tastes better when you eat it with your family</h1>
            <h3>Veg, Non-Veg and all kind of Snacks are available</h3>
            <div class="category">
                <div class="content">
                <h2>The information of this cafe :</h2>
                <table class="content-table">
                            <thead>
                                <tr>
                                <th>Cafe Name</th>
                                <th>Food Name</th>
                                <th>Food Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                <td><%= @cafe_food.cafe.name %></td>
                                <td><%= @cafe_food.food.name %></td>
                                <td><%= @cafe_food.price %></td>
                                </tr>
                            </tbody>
                        </table>
                      
                </div>
            </div>
        </div>
    </showcase> 
<!--   END OF SHOWCASE  -->

</body>
</html>